{% set name = "jsoncpp" %}
{% set version = "1.9.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/open-source-parsers/{{ name }}/archive/{{ version }}.tar.gz
  sha256: f93b6dd7ce796b13d02c108bc9f79812245a82e577581c4c9aabe57075c90ea2
  patches:
    - cmake_min_version.patch

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('jsoncpp', max_pin='x.x.x') }}

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler("cxx") }}
    - cmake
    - make        # [unix]
    - pkg-config  # [unix]
    - python

about:
  home: https://github.com/open-source-parsers/jsoncpp
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: A C++ library for interacting with JSON.
  description: |
    JsonCpp is a C++ library that allows manipulating JSON values, including
    serialization and deserialization to and from strings. It can also preserve
    existing comment in unserialization/serialization steps, making it a
    convenient format to store user input files.
  dev_url: https://github.com/open-source-parsers/jsoncpp
  doc_url: https://open-source-parsers.github.io/jsoncpp-docs/doxygen/index.html

extra:
  recipe-maintainers:
    - jakirkham
    - stuarteberg
    - marcelotrevisani
    - matthiasdiener
