{% set version = "1.9.4" %}

package:
  name: jsoncpp
  version: {{ version }}

source:
  fn: jsoncpp-{{ version }}.tar.gz
  url: https://github.com/open-source-parsers/jsoncpp/archive/{{ version }}.tar.gz
  sha256: e34a628a8142643b976c7233ef381457efad79468c67cb1ae0b83a33d7493999

build:
  number: 0
  features:
    - vc{{ vc }}  # [win]

requirements:
  host:
    - cmake >3.1
    - pkg-config  # [unix]
    - msinttypes  # [win and py27]

  build:
    - {{ compiler('cxx') }}

test:
  commands:
    # Verify headers are present.
    - test -f "${PREFIX}/include/json/json.h"      # [unix]
    - if not exist %LIBRARY_INC%\\json\\json.h exit 1  # [win]

    # Verify pkg-config file is present.
    - test -f "${PREFIX}/lib/pkgconfig/jsoncpp.pc"  # [unix]

    # Verify libraries are present.
    - test -f "${PREFIX}/lib/libjsoncpp_static.a"   # [unix]
    - if not exist %LIBRARY_BIN%\\jsoncpp.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\jsoncpp.lib exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\jsoncpp_static.lib exit 1  # [win]

about:
  home: https://github.com/open-source-parsers/jsoncpp
  license: Public Domain/MIT
  license_file: LICENSE
  summary: A C++ library for interacting with JSON.
  description: |
    JsonCpp is a C++ library that allows manipulating JSON values, including
    serialization and deserialization to and from strings. It can also preserve
    existing comment in unserialization/serialization steps, making it a
    convenient format to store user input files.

extra:
  recipe-maintainers:
    - jakirkham
    - stuarteberg
    - nehaljwani
