travis:
  secure:
    BINSTAR_TOKEN: neWVZJ0735h0shtN8xaIj/kmmVJYF4H/OvwTMDf6Xl6nGek8yLAxkP2MFPrhf/Lhf5cNjzkI1ByEGdzkFUVUePB1mIlqovc0Hf7rqmSJ7H/PC27kzgKotFoHuhEPulcs3Vu+w7wFL+sMzdHRhsIiR/GNikCSuP6/2axItADJsVMddGTyiruYUK/6hgYG8/8EXP2en+ojDd7xMt1aLGDI/cz7ZM5NLaSk2/NK5lEOP61dECSEjYPwfRyV1rWEs/fCfd9W4CbO7BKErdul3iNaHj5BfRg7+Z6t4ZZmx1F+wiS9R9WwgOMCdyLNQqKhwJfsAgcF9Z6cYTT0axiBZR71PKdLRYWJBhS+eQ5zTkZ1ahvx5oLryepwTCl1xLaItffW5V4e5JEdu62sM7kzavGmNwuhhuX+uJPBsKNCi4tCh4O0Gn3q3d6Hui6A48Rl55kxFhmu9uOtFPKS/diE56jp2Q5/0sgi5hmg6Dh26txXSezLBEJZleuIFpEGWOIkYmSyAfUpwqKn7B9QGTCcbmBOffWDWGvfD3CjqEjLmTDjswqSoFIFZVo6Gogwm67NdZavKa+R1tlykqHmP8y03t0SDLQg7EtnmGfnqbsHWEn9uvY18ee3eHDryiVDQ20ASHsgxzJhh/8Aic/KtwrWyT0cCbgNuzTQYnOUQrMLvXYEvh8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
